name: TeleportScroll
version: 1.0
author: Sven Johnson
main: io.sjohnson.teleportscroll.Main
api-version: 1.18
commands:
  rename:
    description: renames teleport scroll
    usage: /<command> new name
  copy:
    description: copies a teleport scroll
    usage: /<command>
  spawnscroll:
    description: spawns a teleport scroll
    usage: /<command> tier quantity
  lifesaver:
    description: spawns a lifesaver
    usage: /<command> quantity
  teleportbook:
    description: manipulates the teleport book
    usage: none
  dev:
    description: developer use only
    usage: /<command>